version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      GROQ_API_KEY: "${GROQ_API_KEY}"
    volumes:
      - .:/app